version: "3.9"


services:

  mongo:
    image: mongo
    restart: always
    container_name: weather-mongo
    ports:
      - "27017:27017"
  server:
    image: kooozel/weather-app:latest
    restart: always
    container_name: weather-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=docker